In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('country_vaccinations.csv')
data.head()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Albania,ALB,2021-01-10,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
1,Albania,ALB,2021-01-11,NaN,NaN,NaN,NaN,64.0,NaN,NaN,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
2,Albania,ALB,2021-01-12,128.0,128.0,NaN,NaN,64.0,0.00,0.00,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
3,Albania,ALB,2021-01-13,188.0,188.0,NaN,60.0,63.0,0.01,0.01,NaN,22.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...
4,Albania,ALB,2021-01-14,266.0,266.0,NaN,78.0,66.0,0.01,0.01,NaN,23.0,Pfizer/BioNTech,Ministry of Health,https://shendetesia.gov.al/covid19-ministria-e...

In [3]:
data.sample(10)

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
3649,Netherlands,NLD,2021-01-26,NaN,NaN,NaN,NaN,15141.0,NaN,NaN,NaN,884.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",National Institute for Public Health and the E...,https://www.rivm.nl/covid-19-vaccinatie/cijfer...
4022,Peru,PER,2021-02-16,NaN,128926.0,NaN,NaN,NaN,NaN,0.39,NaN,NaN,Sinopharm/Beijing,Ministry of Health,https://www.datosabiertos.gob.pe/dataset/vacun...
254,Austria,AUT,2021-01-25,204869.0,200132.0,4737.0,1454.0,12084.0,2.27,2.22,0.05,1342.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Ministry of Health,https://info.gesundheitsministerium.gv.at/open...
4275,Romania,ROU,2020-12-29,2778.0,2778.0,NaN,712.0,906.0,0.01,0.01,NaN,47.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Government of Romania,https://datelazi.ro/
5637,Wales,NaN,2021-02-05,559468.0,556997.0,2471.0,34791.0,25788.0,17.74,17.67,0.08,8179.0,"Oxford/AstraZeneca, Pfizer/BioNTech",Government of the United Kingdom,https://coronavirus.data.gov.uk/details/health...
3679,Netherlands,NLD,2021-02-25,NaN,NaN,NaN,NaN,40436.0,NaN,NaN,NaN,2360.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",National Institute for Public Health and the E...,https://www.rivm.nl/covid-19-vaccinatie/cijfer...
2799,Italy,ITA,2021-01-20,1313843.0,1299856.0,13987.0,29928.0,55278.0,2.17,2.15,0.02,914.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Extraordinary commissioner for the Covid-19 em...,https://github.com/italia/covid19-opendata-vac...
422,Bahrain,BHR,2021-03-05,NaN,307142.0,NaN,NaN,7712.0,NaN,18.05,NaN,4532.0,"Oxford/AstraZeneca, Pfizer/BioNTech, Sinopharm...",Ministry of Health,https://twitter.com/MOH_Bahrain/status/1369392...
812,Bulgaria,BGR,2021-02-07,57038.0,39646.0,17392.0,22.0,2273.0,0.82,0.57,0.25,327.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Ministry of Health,https://coronavirus.bg/bg/statistika
1777,Estonia,EST,2021-02-08,53481.0,35917.0,17564.0,57.0,2127.0,4.03,2.71,1.32,1603.0,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",National Health Board,https://www.terviseamet.ee/et/uudised/covid-19...

In [4]:
data.columns

Index(['country', 'iso_code', 'date', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated',
       'daily_vaccinations_raw', 'daily_vaccinations',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'daily_vaccinations_per_million',
       'vaccines', 'source_name', 'source_website'],
      dtype='object')

In [5]:
data.shape

(5689, 15)

In [6]:
data.isnull().sum()

#We can see that in this data is a lot of nulls. The most complete column is "daily_vaccinations", so I'm gonna use this column
#later.

country                                   0
iso_code                                344
date                                      0
total_vaccinations                     2055
people_vaccinated                      2463
people_fully_vaccinated                3490
daily_vaccinations_raw                 2631
daily_vaccinations                      186
total_vaccinations_per_hundred         2055
people_vaccinated_per_hundred          2463
people_fully_vaccinated_per_hundred    3490
daily_vaccinations_per_million          186
vaccines                                  0
source_name                               0
source_website                            0
dtype: int64

In [7]:
data.dtypes

country                                 object
iso_code                                object
date                                    object
total_vaccinations                     float64
people_vaccinated                      float64
people_fully_vaccinated                float64
daily_vaccinations_raw                 float64
daily_vaccinations                     float64
total_vaccinations_per_hundred         float64
people_vaccinated_per_hundred          float64
people_fully_vaccinated_per_hundred    float64
daily_vaccinations_per_million         float64
vaccines                                object
source_name                             object
source_website                          object
dtype: object

In [8]:
#First, I would like to analize data about covid vaccinations in Poland. 

data[data.country == 'Poland'].describe()

#Some of this measures doesn't make sense for all the columns, e.x. total_vaccinations which is cumulative sum for a 
#daily_vaccinations

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
count,6.300000e+01,6.300000e+01,4.400000e+01,53.000000,71.00000,63.000000,63.000000,44.000000,71.000000
mean,1.411120e+06,1.012344e+06,5.709745e+05,51303.320755,55380.15493,3.728571,2.675238,1.508864,1463.253521
std,1.217198e+06,7.573946e+05,4.644958e+05,42949.755872,27270.00417,3.216090,2.001333,1.227778,720.516436
min,2.000000e+03,2.000000e+03,6.710000e+02,442.000000,4300.00000,0.010000,0.010000,0.000000,114.000000
25%,3.898460e+05,3.898460e+05,1.717908e+05,19973.000000,32441.50000,1.030000,1.030000,0.452500,857.000000
50%,1.141081e+06,9.456000e+05,4.663210e+05,41387.000000,64577.00000,3.020000,2.500000,1.230000,1706.000000
75%,2.194632e+06,1.519824e+06,9.267528e+05,69513.000000,82767.50000,5.795000,4.020000,2.452500,2187.000000
max,4.086863e+06,2.641693e+06,1.445170e+06,172261.000000,94476.00000,10.800000,6.980000,3.820000,2496.000000

In [9]:
#Compare total_vaccinations for the latest date with daily_vaccinations cumulative sum for the latest date

daily_vaccinations_poland = (
    data[data.country == 'Poland'][['country', 'date', 'total_vaccinations', 'daily_vaccinations']]
    .sort_values(by='date', ascending=True)
    
)

daily_vaccinations_poland['cumsum'] = daily_vaccinations_poland['daily_vaccinations'].cumsum()
daily_vaccinations_poland.tail(1)

     country        date  total_vaccinations  daily_vaccinations     cumsum
4123  Poland  2021-03-09           4086863.0             83642.0  3931991.0

In [10]:
#We can see that these two numbers ('total vaccinations' and 'cumsum' of daily vaccinations differs, 
#but what causes that difference? We can check if there are any missing data in daily_vaccinations.

daily_vaccinations_poland['daily_vaccinations'].isnull().sum()

1

In [11]:
data[data.country == 'Poland'][data.daily_vaccinations.isnull()]

C:\Users\Kamila\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
4052,Poland,POL,2020-12-28,2000.0,2000.0,NaN,NaN,NaN,0.01,0.01,NaN,NaN,"Moderna, Oxford/AstraZeneca, Pfizer/BioNTech",Ministry of Health,https://www.gov.pl/web/szczepimysie/raport-szc...

In [12]:
#There is only one row with missing data about 'daily_vaccinations' and it is the oldest date.
#Total_vaccinations on this date is equal to 2000, so that doesn't explain missing 150 000 vaccinations.
#I want to check if data is correct in one more way.

In [13]:
#Let's have a look on three head rows. 
#Total number of vaccinations on day 2020-12-29:
total_1 = data[(data.country == 'Poland') & (data.date=='2020-12-29')].loc[:, 'total_vaccinations'].values[0]
total_1

6300.0

In [14]:
#Total number of vaccinations on day 2020-12-30:
total_2 = data[(data.country == 'Poland') & (data.date=='2020-12-30')].loc[:, 'total_vaccinations'].values[0]
total_2

36300.0

In [15]:
#Total vaccinations on 2020-12-30 should equal total_vacinations on 2020-12-29 + daily_vaccinations for 2020-12-30:
daily_2 = data[(data.country == 'Poland') & (data.date=='2020-12-30')].loc[:, 'daily_vaccinations'].values[0] 
daily_2 + total_1

23450.0

In [16]:
total_2 == total_1 + daily_2

False

In [17]:
#This calculations shows that numbers of vaccinations given by government are not quite correct.

In [18]:
#Compare data concerning Poland to data of statistical country.
world_statistics = data.describe()
world_statistics

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
count,3.634000e+03,3.226000e+03,2.199000e+03,3.058000e+03,5.503000e+03,3634.000000,3226.000000,2199.000000,5503.000000
mean,2.064051e+06,1.708466e+06,6.396015e+05,8.129581e+04,5.809493e+04,8.265446,6.501587,2.784825,2545.302744
std,7.079363e+06,5.376833e+06,2.540051e+06,2.355711e+05,1.868000e+05,15.278334,10.603580,6.352956,4373.580976
min,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,0.000000,0.000000,0.000000,0.000000
25%,3.416825e+04,3.315775e+04,1.493000e+04,2.535250e+03,1.131000e+03,0.640000,0.680000,0.290000,347.000000
50%,2.343405e+05,2.216525e+05,7.942900e+04,1.307250e+04,6.552000e+03,3.115000,2.810000,1.090000,1160.000000
75%,1.076734e+06,9.019288e+05,4.120510e+05,5.698375e+04,2.936000e+04,8.187500,6.410000,2.480000,2643.500000
max,9.369260e+07,6.108853e+07,3.210206e+07,2.904229e+06,2.169981e+06,131.310000,84.390000,46.920000,54264.000000

In [19]:
#How many countries is included in this data? 
data.country.nunique()

129

In [20]:
world_statistics/129

,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million
count,28.170543,25.007752,17.046512,23.705426,42.658915,28.170543,25.007752,17.046512,42.658915
mean,16000.392608,13243.920467,4958.150995,630.200057,450.348312,0.064073,0.050400,0.021588,19.731029
std,54878.783285,41680.876045,19690.317984,1826.132289,1448.061936,0.118437,0.082198,0.049248,33.903728
min,0.000000,0.000000,0.007752,0.000000,0.007752,0.000000,0.000000,0.000000,0.000000
25%,264.870155,257.036822,115.736434,19.653101,8.767442,0.004961,0.005271,0.002248,2.689922
50%,1816.593023,1718.236434,615.728682,101.337209,50.790698,0.024147,0.021783,0.008450,8.992248
75%,8346.775194,6991.695736,3194.193798,441.734496,227.596899,0.063469,0.049690,0.019225,20.492248
max,726299.209302,473554.472868,248853.186047,22513.403101,16821.558140,1.017907,0.654186,0.363721,420.651163

In [30]:
#Drop rows with missing data in column 'daily vaccinations'

daily_vaccinations = data.dropna(subset=['daily_vaccinations'])

daily_vaccinations.isnull().sum()

country                                   0
iso_code                                340
date                                      0
total_vaccinations                     2012
people_vaccinated                      2419
people_fully_vaccinated                3310
daily_vaccinations_raw                 2458
daily_vaccinations                        0
total_vaccinations_per_hundred         2012
people_vaccinated_per_hundred          2419
people_fully_vaccinated_per_hundred    3310
daily_vaccinations_per_million            0
vaccines                                  0
source_name                               0
source_website                            0
dtype: int64

In [62]:
daily_vaccinations_countries = (
    daily_vaccinations[['country', 'daily_vaccinations']]
    .groupby('country')
    .mean()
    .rename(columns={'daily_vaccinations': 'daily_vaccinations_mean'})
    .sort_values(by='daily_vaccinations_mean', ascending=False)
    
)
daily_vaccinations_countries.head(20)

                      daily_vaccinations_mean
country
United States                    1.105057e+06
China                            6.625035e+05
India                            3.954802e+05
United Kingdom                   2.699429e+05
England                          2.276032e+05
Brazil                           2.006456e+05
Turkey                           1.916933e+05
Morocco                          1.145606e+05
Israel                           1.094884e+05
Germany                          1.055197e+05
Bangladesh                       8.798450e+04
United Arab Emirates             8.792100e+04
France                           7.655423e+04
Russia                           7.529940e+04
Italy                            7.380744e+04
Spain                            7.243592e+04
Indonesia                        6.430876e+04
Chile                            6.227080e+04
Poland                           5.538015e+04
Mexico                           3.726643e+04